### ISSUE TITLE
Error message do not propegate in meaningful way to the python layer

### ISSUE THREAD

**Issue by haimav** [xdata-skylark/libskylark#11]
One idea is to serialize in json the exceptions generated by the C++ layer.

**Comment by iff** [comment]
Aside from the [strerr](https://github.com/xdata-skylark/libskylark/blob/46c889cec9b1180120a7d63158cede53fabf2df9/capi/basec.hpp#L25) like functionality that we provide?

**Comment by haimav** [comment]
Yes, I meant something that will print the information that is issued at the point of exception to understand the reason instead of "something failed in the sketching layer'.

Anyway, I implemented it. You can take a look to see how (in development branch).

**Comment by iff** [comment]
Ok, that functionality makes sense. 
 
The `lastexception` global static is probably not thread safe, right?
 
-- Yves--Yves Ineichen, PhDResearch Staff MemberIBM Research - ZurichCognitive Computing SolutionsSaumerstrasse 4, 8803 Rueschlikon - Switzerlandtel: +41 44 724 8587e-mail: yin@zurich.ibm.com
 
 
----- Original message -----From: Haim Avron <notifications@github.com>To: xdata-skylark/libskylark <libskylark@noreply.github.com>Cc: Yves Ineichen <yin@zurich.ibm.com>, Comment <comment@noreply.github.com>Subject: Re: [xdata-skylark/libskylark] Error message do not propegate in meaningful way to the python layer (#11)Date: Sat, Jun 11, 2016 8:10 AM 
Yes, I meant something that will print the information that is issued at the point of exception to understand the reason instead of "something failed in the sketching layer'.
Anyway, I implemented it. You can take a look to see how (in development branch).

**Comment by haimav** [comment]
mmm.... didn't think of that too much. exception_ptr is technically thread safe, but I am not sure it is enough. In general I would think we use OpenMP for threading and that all exception handling should be done outside parallel region. But I don't think this is really the case in the code. The whole issue of exception handling with OpenMP is not clear to me.
